using System;
using System.Drawing;
using System.Net.Security;

namespace TwoFactorAuthNet.Providers.Qr
{
    /// <summary>
    /// Provides QR codes generated by QRickit.
    /// </summary>
    /// <seealso href="http://qrickit.com/qrickit_apps/qrickit_api.php"/>.
    public class QRicketQrCodeProvider : BaseHttpQrCodeProvider, IQrCodeProvider
    {
        /// <summary>
        /// Represents the filetype to be returned.
        /// </summary>
        public enum QRicketImageFormat
        {
            /// <summary>PNG</summary>
            Png = 'p',
            /// <summary>GIF</summary>
            Gif = 'g',
            /// <summary>JPEG</summary>
            Jpeg = 'j'
        }

        /// <summary>
        /// Gets the <see cref="ErrorCorrectionLevel"/> for the QR code.
        /// </summary>
        public ErrorCorrectionLevel ErrorCorrectionLevel { get; private set; }

        /// <summary>
        /// Gets the background color to be used for the QR code.
        /// </summary>
        public Color BackgroundColor { get; private set; }

        /// <summary>
        /// Gets the foreground color to be used for the QR code.
        /// </summary>
        public Color ForegroundColor { get; private set; }

        /// <summary>
        /// Gets the <see cref="QRicketImageFormat"/> of the QR code.
        /// </summary>
        public QRicketImageFormat ImageFormat { get; private set; }

        /// <summary>
        /// <see cref="BaseHttpQrCodeProvider.BaseUri"/> for this QR code provider.
        /// </summary>
        private static readonly Uri baseuri = new Uri("http://qrickit.com/api/qr");

        /// <summary>
        /// Initializes a new instance of a <see cref="QRicketQrCodeProvider"/> with the default
        /// <see cref="ErrorCorrectionLevel"/> (<see cref="F:TwoFactorAuthNet.Providers.Qr.ErrorCorrectionLevel.Low"/>),
        /// <see cref="BackgroundColor"/> (<see cref="Color.White"/>), <see cref="ForegroundColor"/>
        /// (<see cref="Color.Black"/>), <see cref="QRicketImageFormat">ImageFormat</see>
        /// (<see cref="QRicketImageFormat.Png"/>) and <see cref="RemoteCertificateValidationCallback"/>.
        /// </summary>
        public QRicketQrCodeProvider()
            : this(ErrorCorrectionLevel.Low)
        { }

        /// <summary>
        /// Initializes a new instance of a <see cref="QRicketQrCodeProvider"/> with the specified
        /// <see cref="ErrorCorrectionLevel"/> and default <see cref="BackgroundColor"/> (<see cref="Color.White"/>),
        /// <see cref="ForegroundColor"/> (<see cref="Color.Black"/>), <see cref="QRicketImageFormat">ImageFormat</see> 
        /// (<see cref="QRicketImageFormat.Png"/>) and <see cref="RemoteCertificateValidationCallback"/>.
        /// </summary>
        /// <param name="errorCorrectionLevel">The <see cref="ErrorCorrectionLevel"/> to use when generating QR codes.</param>
        public QRicketQrCodeProvider(ErrorCorrectionLevel errorCorrectionLevel)
            : this(errorCorrectionLevel, Color.White)
        { }


        /// <summary>
        /// Initializes a new instance of a <see cref="QRicketQrCodeProvider"/> with the specified
        /// <see cref="ErrorCorrectionLevel"/>, <see cref="BackgroundColor"/> and default <see cref="ForegroundColor"/> 
        /// (<see cref="Color.Black"/>), <see cref="QRicketImageFormat">ImageFormat</see> 
        /// (<see cref="QRicketImageFormat.Png"/>) and <see cref="RemoteCertificateValidationCallback"/>.
        /// </summary>
        /// <param name="errorCorrectionLevel">The <see cref="ErrorCorrectionLevel"/> to use when generating QR codes.</param>
        /// <param name="backgroundColor">The background color to be used for the QR code.</param>
        public QRicketQrCodeProvider(ErrorCorrectionLevel errorCorrectionLevel, Color backgroundColor)
            : this(errorCorrectionLevel, backgroundColor, Color.Black)
        { }

        /// <summary>
        /// Initializes a new instance of a <see cref="QRicketQrCodeProvider"/> with the specified
        /// <see cref="ErrorCorrectionLevel"/>, <see cref="BackgroundColor"/>, <see cref="ForegroundColor"/> and
        /// default <see cref="QRicketImageFormat">ImageFormat</see> (<see cref="QRicketImageFormat.Png"/>) and 
        /// <see cref="RemoteCertificateValidationCallback"/>.
        /// </summary>
        /// <param name="errorCorrectionLevel">The <see cref="ErrorCorrectionLevel"/> to use when generating QR codes.</param>
        /// <param name="backgroundColor">The background color to be used for the QR code.</param>
        /// <param name="foregroundColor">The foreground color to be used for the QR code.</param>
        public QRicketQrCodeProvider(ErrorCorrectionLevel errorCorrectionLevel, Color backgroundColor, Color foregroundColor)
            : this(errorCorrectionLevel, backgroundColor, foregroundColor, QRicketImageFormat.Png)
        { }

        /// <summary>
        /// Initializes a new instance of a <see cref="QRicketQrCodeProvider"/> with the specified
        /// <see cref="ErrorCorrectionLevel"/>, <see cref="BackgroundColor"/>, <see cref="ForegroundColor"/>, 
        /// <see cref="QRicketImageFormat">ImageFormat</see> and default
        /// <see cref="RemoteCertificateValidationCallback"/>.
        /// </summary>
        /// <param name="errorCorrectionLevel">The <see cref="ErrorCorrectionLevel"/> to use when generating QR codes.</param>
        /// <param name="backgroundColor">The background color to be used for the QR code.</param>
        /// <param name="foregroundColor">The foreground color to be used for the QR code.</param>
        /// <param name="imageFormat">The <see cref="QRicketImageFormat"/> of the QR code.</param>
        public QRicketQrCodeProvider(ErrorCorrectionLevel errorCorrectionLevel, Color backgroundColor, Color foregroundColor, QRicketImageFormat imageFormat)
            : this(errorCorrectionLevel, backgroundColor, foregroundColor, imageFormat, null)
        { }

        /// <summary>
        /// Initializes a new instance of a <see cref="QRicketQrCodeProvider"/> with the specified
        /// <see cref="ErrorCorrectionLevel"/>, <see cref="BackgroundColor"/>, <see cref="ForegroundColor"/>, 
        /// <see cref="QRicketImageFormat">ImageFormat</see> and <see cref="RemoteCertificateValidationCallback"/>.
        /// </summary>
        /// <param name="errorCorrectionLevel">The <see cref="ErrorCorrectionLevel"/> to use when generating QR codes.</param>
        /// <param name="backgroundColor">The background color to be used for the QR code.</param>
        /// <param name="foregroundColor">The foreground color to be used for the QR code.</param>
        /// <param name="imageFormat">The <see cref="QRicketImageFormat"/> of the QR code.</param>
        /// <param name="remoteCertificateValidationCallback">
        /// The <see cref="RemoteCertificateValidationCallback"/> to use when generating QR codes.
        /// </param>
        /// <exception cref="ArgumentOutOfRangeException">
        /// Thrown when an invalid <see cref="ErrorCorrectionLevel"/> or <see cref="QRicketImageFormat"/> is specified.
        /// </exception>
        public QRicketQrCodeProvider(ErrorCorrectionLevel errorCorrectionLevel, Color backgroundColor, Color foregroundColor, QRicketImageFormat imageFormat, RemoteCertificateValidationCallback remoteCertificateValidationCallback)
            : base(baseuri, remoteCertificateValidationCallback)
        {
            if (!Enum.IsDefined(typeof(ErrorCorrectionLevel), errorCorrectionLevel))
                throw new ArgumentOutOfRangeException("errorCorrectionLevel");
            this.ErrorCorrectionLevel = errorCorrectionLevel;

            this.BackgroundColor = backgroundColor;
            this.ForegroundColor = foregroundColor;

            if (!Enum.IsDefined(typeof(QRicketImageFormat), imageFormat))
                throw new ArgumentOutOfRangeException("imageFormat");
            this.ImageFormat = imageFormat;
        }

        /// <summary>
        /// Gets the MIME type of the image.
        /// </summary>
        /// <returns>Returns the MIME type of the image.</returns>
        /// <seealso cref="IQrCodeProvider"/>
        /// <exception cref="InvalidOperationException">
        /// Thrown when an unknown <see cref="QRicketImageFormat"/> is used.
        /// </exception>
        public string GetMimeType()
        {
            switch (this.ImageFormat)
            {
                case QRicketImageFormat.Png:
                    return "image/png";
                case QRicketImageFormat.Gif:
                    return "image/gif";
                case QRicketImageFormat.Jpeg:
                    return "image/jpeg";
            }
            throw new InvalidOperationException("Unknown imageformat");
        }

        /// <summary>
        /// Downloads / retrieves / generates a QR code as image.
        /// </summary>
        /// <param name="text">The text to encode in the QR code.</param>
        /// <param name="size">The desired size (width and height equal) for the image.</param>
        /// <returns>Returns the binary representation of the image.</returns>
        /// <seealso cref="IQrCodeProvider"/>
        public byte[] GetQrCodeImage(string text, int size)
        {
            return this.DownloadData(this.GetUri(text, size));
        }

        /// <summary>
        /// Builds an <see cref="Uri"/> based on the instance's <see cref="BaseHttpQrCodeProvider.BaseUri"/>.
        /// </summary>
        /// <param name="qrText">The text to encode in the QR code.</param>
        /// <param name="size">The desired size of the QR code.</param>
        /// <returns>A <see cref="Uri"/> to the QR code.</returns>
        private Uri GetUri(string qrText, int size)
        {
            return new Uri(this.BaseUri,
                "?qrsize=" + size
                + "&e=" + Char.ToLowerInvariant(((char)this.ErrorCorrectionLevel))
                + "&bgdcolor=" + Color2Hex(this.BackgroundColor)
                + "&fgdcolor=" + Color2Hex(this.ForegroundColor)
                + "&t=" + (char)this.ImageFormat
                + "&d=" + Uri.EscapeDataString(qrText)
            );
        }
    }
}
